### ISSUE TITLE
ex reborn!!!!!

### ISSUE THREAD

**Issue by farteryhr** [Shots243/ModePile#4]
firstly i'm so honored to find that t-ex have been cloned!
(i decided to change its name to t-ex in 2014 because there was once it was detected containing "sex" by some filter even when named "tetris-ex") (and it's shorter) (also for not being ****®-ed y'know) (casing doesn't matter because i come from visual basic) (x

then findings comes....
TetrisEXWallkick.java the CW table isn't mirrored despite the comment stating it should be mirrored. 🤔
then comes to the hard part: the condition to use the "moving" tables. it's not simply "the moving button is pushed" (at least both may be pushed while in the DAS system only one can be functioning). the condition should be "the DAS is functioning but blocked (by mino or wall) (in the direction it's functioning)", like saying "there's pressure against the wall."
this s some fundamental difference and the "failed-to-move" information from DAS system needs to be passed to the wallkick subsystem.

back to that year i'm scared by the long long code of nullpomino's onMove routine so i haven't manage to read through it yet 😶... (and now i'm still not confident to change this)..

minor ones, for example the scoring (well it's up to you since it's a remastering), but the original scoring scheme favors clearing the field as much as possible near x99 and getting more pieces for free to stack for tetris. also piece placement worths a lot and higher placement rewards even more. (like in Tengen NES version) (it even used to be rewarding clearing higher rows, i don't remember when i changed it to the current one..) it was some good old memory having a score war with Kitaru around 1.3~1.5M....

the post-M5 skin, i'm also not a fan of torturing players' (my) eyes with `[]`s... in the VB6 version it's rendered in "full outline" (much like in DTET after you won a battle, the active piece is also outlined), and in the flash version i just decided to simply use white skin.

about WTF stage... well i don't remember whether i have passed M9 in a legit way... then... who cares (slap

and there's a cheat button with which also enables my early attempt of backfire™ series feature... not sure if you want it (((

my best wish goes to the XRS being implemented "well", in fact the wallkick sequence has had its last minor tweak also in 2014, according to feedback, it could even be further adjusted/extended if it makes better playing (and i don't mind wilder o-spin))

i've just managed to find and extract the old code ("officially") (though it seems not that necessary cuz u must've got it....): https://github.com/farteryhr/labs/blob/master/t-ex_core.as

thanks for the reborn, even before me trying to do so in my tetr.js mod🤣

**Comment by Shots243** [comment]
Thank you for the game, it's a very interesting idea and quite fun to implement! It's also an honour for this little project to be noticed!

As for the reported findings:
- I'm not sure how I forgot to mirror the X coordinates in the base kick tests, but that's fixed now (hopefully).
- As of right now NullpoMino's wallkick system doesn't provide a way of passing DAS charge info to the wallkick function sadly (only the [Controller](https://github.com/nullpomino/nullpomino/blob/master/nullpomino-core/src/main/java/mu/nu/nullpo/game/component/Controller.java) class, which does not hold DAS info), so the button press only detection is somewhat of a compromise. The closest is that the [Controller](https://github.com/nullpomino/nullpomino/blob/master/nullpomino-core/src/main/java/mu/nu/nullpo/game/component/Controller.java) class holds info on how long a button has been pressed, but there's no way to tell it the threshold for hold time until it should use the movement tables rather than the base tables. However, reworking the wallkick class to have some public fields seems to work as Java can check whether the instance type is correct, and passing values into those fields seems to fix this.
- I think I borrowed the scoring system from TGM1 as I couldn't figure out the scoring system used at the time (more on this in a bit). I think I'll switch to the actual system as it felt less combo-weighted compared to TGM1's and due to it rewarding higher play.
- The `[]` blocks were a bit hard to see, yeah. I think at the time of making the clone I wasn't quite sure on how to override the colours of the incoming next pieces properly (I've only ever had experience with the Flash version of T-EX). That's fixed now.
- With the WTF level, I think I just added big mode since I wasn't sure what it did in the original game (I think the highest I've ever reached was M8 in the Flash version on the Modern setting).
- Backfire would be an interesting thing to try and implement... might try it some time and put it in as a toggleable (but unranked) setting.
- About the code, I used a Flash decompiler to look into the Flash version's source to check the speed tables (I apologise if that's a bit uncalled for), but that was where I kinda ran out of knowledge to look at for the scoring logic and stuff since the decompiler gave code with a lot of auto-named variables, no comments and in a bit of a cluttered way so that was why I ended up improvising the scoring and movement checking. Thank you for the official source, that will help a lot when trying to rewrite the scoring later.

Thank you so much again for looking at this and giving feedback! Things should have been changed as of commit [794ff800e3772618ee2faf236744cbc2473956df](https://github.com/Shots243/ModePile/commit/794ff800e3772618ee2faf236744cbc2473956df).

**Comment by farteryhr** [comment]
in fact my source is also decompiled from my own previous release because i lost the original .fla due to disk failure 😂 (made some last tweaks to it, then compile to swf again, renamed and released as "T-ex returns", that's all what happened in 2014)

and since i'm using few local variables, mostly global, so their names are retained.
(if you're scared by `kcmr kpmr`-like names...... it stands for Key Counter/Pushed of Move Right!!! hahaha (boom)) (once you get this, believe me it's not that hard to read (?????))
score is one of the global variables too, named nscore.

**Comment by Shots243** [comment]
I'm not going to lie, I didn't notice the soft drop / hard drop reversal at all until it was pointed out.
Come to think of it, I don't think I've seen anyone else notice (at least, anyone who I know plays T-ex who I talk to).

**Comment by farteryhr** [comment]
many reported to me *facepalm*
maybe others are just like "hmmmmm?????????????????" and 1 min later "ok just swap it let me play a game"...

**Comment by farteryhr** [comment]
some even more details about the rule file..
- hidden height: 2 (or more)
https://github.com/farteryhr/labs/blob/master/t-ex_core.as#L1328 https://github.com/farteryhr/labs/blob/master/t-ex_core.as#L473
- can't use initial hold until pressed again: true
https://github.com/farteryhr/labs/blob/master/t-ex_core.as#L1126
- can't use initial rotation until release the button: true
https://github.com/farteryhr/labs/blob/master/t-ex_core.as#L678
kc** for rotate / hold smells like some state machine: 1 = to do (if blocked, won't turn to 2), 2 = done and the button is still pushed (turns to 0 only when released). it ensures single button press won't trigger twice.
only zero/one rotation button in ARE will be 1, kpr2kcr() on one key-down turns others pushed rotations to 2.
the style of initial hold style seems not currently implemented in nullpomino: also triggers by key-down, and exchanges hold with next instantly, there's no way to undo. not so mandatory though.
there's also one thing common with DTET that nullopomino doesn't have: (in active time) if rotation fails, it keeps trying on the following frames until succeeds.
- when both left and right are pressed, use previous button: false
- allow diagonal move: true
these are pretty straightforward, but affects movements quite a lot and i can notice them.

more detailed things with DAS charge... well let it go... though i think it needs investigation also for fixing game modes the original nullpomino emulated...

my analysis of root of the problem from the original with initial movement/IRS: (also involves DRS)
https://github.com/nullpomino/nullpomino/commit/f779979bb67781070e9a0712f671aaefe0ea3652
